# 接口数据模板，对应接口的className要相同

# 基类，不需要使用
BaseAPI:
  path: "/api/mgr/sq_mgr/"
  add: {}
  edit: {}
  delete: {}
  list: {}

# 课程类接口数据模板
CourseAPI:
  path: "/api/mgr/sq_mgr/"
  add: {
      "action": "add_course",
      "data": {
          "name": "初中化学",
          "desc": "描述初中化学课程",
          "display_idx": "10"
      }
  }
  edit: {
        "action": "modify_course",
        "id": 100,
        "newdata": {
             "name": "新初中化学",
             "desc": "描述新初中化学课程",
             "display_idx": 100
        }
  }
  list: {
        "action": "list_course",
        "pagenum": 1,
        "pagesize": 20
  }
  delete: {
        "action": "delete_course",
        "id": 100
  }

# 教师类接口数据模板
TeacherAPI:
  path: "/api/mgr/sq_mgr/"
  add: {
      "action": "add_teacher",
      "data": {
            "username": "username",
            "password": "123456",
            "realname": "realname",
            "desc": "描述字段",
            "display_idx": 100,
            "courses":[],
      }
  }
  edit: {
      "action": "modify_teacher",
      "id": "teacher_id",
      "newdata": {
              "username": "newname",
              "password": "newpassword",
              "realname": "newrealname",
              "desc": "描述修改老师字段",
              "display_idx": 100,
              "courses": [],
      }
  }
  list: {
      "action": "list_teacher",
      "pagenum": 1,
      "pagesize": 20
  }
  delete: {
        "action": "delete_teacher",
        "id": "teacher_id"
  }

# 培训班接口数据模板
TrainingAPI:
  path: "/api/mgr/sq_mgr/"
  add: {
      "action": "add_training",
      "data":{
            "name": "培训班名字",
            "desc": "培训班描述",
            "display_idx": 100,
            "courselist":[]
      }
  }
  edit: {
      "action": "modify_training",
      "id": 123,
      "newdata": {
              "name": "新培训班名字",
              "desc": "培训班新描述",
              "display_idx": 10,
              "courselist": [],
      }
  }
  list: {
      "action": "list_training",
      "pagenum": 1,
      "pagesize": 20
  }
  delete: {
        "action": "delete_training",
        "id": "training_id"
  }

TrainingGradeAPI:
  path: "/api/mgr/sq_mgr/"
  add: {
      "action": "add_training_grade",
      "data": {
            "name": "培训班期名称",
            "desc": "培训班期描述",
            "display_idx": 20,
            "training_id": "training_id"
      }
  }
  list: {
      "action": "list_training_grade",
      "pagenum": 1,
      "pagesize": 20
  }
  edit: {
      "action": "modify_training_grade",
      "id": "training_grade_id",
      "newdata": {
            "name": "新培训班期名称",
            "desc": "新培训班期描述",
            "display_idx": 20,
             "training_id": ""
      }
  }
  delete: {
        "action": "delete_training_grade",
        "id": "training_grade_id"
  }
